-- Make the schema fit the REAL exported rate config.
--
-- Written after exporting app_rates from the legacy Supabase project. The normalised
-- tables were modelled from the code paths that were ported; the actual config is
-- 40KB and carries three things the schema had nowhere to put. Every statement here
-- is additive and idempotent — nothing is dropped, nothing is rewritten.
--
-- 1. THE ALARM.COM PRICE SHEET  (rate_profile.adc)
--
--    src/lib/adc.js already reads `rates.adc` and expects the whole tree: packages,
--    per-package supervision, metered tiers with max/step/perUnit, Noonlight free
--    units, the LiftMaster surcharge. The rates endpoint never returned an `adc` key,
--    so adcCfg was ALWAYS null and three charges silently priced at zero:
--
--        adc.js:193  supervision       contributed nothing
--        adc.js:202  Noonlight         contributed nothing
--        adc.js:217  LiftMaster        contributed nothing
--
--    That is missing recurring revenue on every commercial quote, not a rounding
--    difference. This column is what makes it reachable.
--
--    Stored as jsonb rather than spread across seven tables ON PURPOSE. It is a
--    VENDOR'S price sheet, not Point 1's rates: Alarm.com reissues it wholesale,
--    nobody here edits one cell of it, and it is consumed as a tree by code that
--    already exists. Normalising it would mean reassembling the identical tree in the
--    API on every request, and turning a sheet reissue into a seven-table diff.
--    Versioning still works, because rate_profile is versioned — publishing a new
--    profile keeps the old sheet intact and auditable.
--
--    Point 1's OWN rates stay normalised. The split is deliberate: things Point 1
--    sets get columns and constraints, a vendor's published sheet gets stored as
--    published.
ALTER TABLE rate_profile ADD COLUMN IF NOT EXISTS adc jsonb;

COMMENT ON COLUMN rate_profile.adc IS
  'Alarm.com wholesale price sheet as published, consumed as a tree by src/lib/adc.js. '
  'Versioned with the profile. Point 1 rates belong in the normalised tables, not here.';

-- 2. SERVICE TIERS CARRY THREE RATES, NOT ONE
--
--    The real config is tierRates.{essential,priority,premier}.{st,th,dt} — straight
--    time, time and a half, double time. tier_rate had a single `rate`, so after-hours
--    and holiday work would have been quoted at the straight-time figure: an
--    undercharge precisely when the work costs most.
--
--    `rate` is kept and left NOT NULL so nothing reading it breaks; the import writes
--    straight time into it. New code should read the three explicit columns.
ALTER TABLE tier_rate ADD COLUMN IF NOT EXISTS straight_time  numeric(10,2);
ALTER TABLE tier_rate ADD COLUMN IF NOT EXISTS time_and_half  numeric(10,2);
ALTER TABLE tier_rate ADD COLUMN IF NOT EXISTS double_time    numeric(10,2);

-- 3. WHEN A CHANGE REQUEST WAS FINISHED
--
--    cr_requests.completed_at exists in the legacy table and had nowhere to land.
--    Deriving it from status='done' loses WHEN, which is the only thing that makes
--    "how long do these take" answerable later.
ALTER TABLE change_request ADD COLUMN IF NOT EXISTS completed_at timestamptz;

-- 4. REFERENCE LISTS — deliberately NOT tied to a rate profile
--
--    The legacy config carries 22 estimators, 18 vendors and 107 manufacturers inside
--    the rates blob. They are not rates, and binding them to rate_profile would mean
--    PUBLISHING A NEW RATE PROFILE TO ADD A COLLEAGUE — a repricing event to record a
--    name. They get their own tables, editable without touching pricing.
--
--    is_active rather than DELETE: an estimator who leaves still appears on quotes
--    they prepared, and deleting the row would orphan that history.
CREATE TABLE IF NOT EXISTS estimator (
  estimator_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         varchar(200) NOT NULL,
  email        varchar(200),
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now()
);
-- Case-insensitive, because 'J.Smith@' and 'j.smith@' are one person and a re-run of
-- the import must not create a second row. Partial, so rows without an email are
-- allowed rather than colliding on NULL.
CREATE UNIQUE INDEX IF NOT EXISTS uq_estimator_email
  ON estimator (lower(email)) WHERE email IS NOT NULL;

CREATE TABLE IF NOT EXISTS vendor (
  vendor_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_key  varchar(80) NOT NULL,
  display     varchar(200) NOT NULL,
  -- The legacy matches vendor names from imported spreadsheets against a list of
  -- aliases. jsonb keeps that list attached to the vendor instead of in code.
  aliases     jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_vendor_key ON vendor (lower(vendor_key));

CREATE TABLE IF NOT EXISTS manufacturer (
  manufacturer_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            varchar(200) NOT NULL,
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_manufacturer_name ON manufacturer (lower(name));

-- 5. WHERE THE LEGACY ROW CAME FROM
--
--    A rehearsal is run repeatedly, and without this an import cannot tell a row it
--    already created from one a person typed. Nullable, so records created in the new
--    app simply have no legacy id, and unique, so a second import updates rather than
--    duplicating.
ALTER TABLE change_request      ADD COLUMN IF NOT EXISTS legacy_id int;
ALTER TABLE change_request_file ADD COLUMN IF NOT EXISTS legacy_id int;
ALTER TABLE change_request_note ADD COLUMN IF NOT EXISTS legacy_id int;

CREATE UNIQUE INDEX IF NOT EXISTS uq_change_request_legacy
  ON change_request (legacy_id) WHERE legacy_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_change_request_file_legacy
  ON change_request_file (legacy_id) WHERE legacy_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_change_request_note_legacy
  ON change_request_note (legacy_id) WHERE legacy_id IS NOT NULL;

-- 6. IDENTITIES THAT HAVE NOT BEEN MAPPED YET
--
--    requester_oid is NOT NULL and means an Entra object id. The legacy rows carry a
--    Supabase UUID, and the two cannot be resolved without a person deciding who is
--    who. The import writes 'supabase:<uuid>' so an unmapped identity is OBVIOUS and
--    greppable, rather than a plausible-looking id that quietly belongs to nobody.
--
--    This is a rehearsal affordance. Before cutover those must be resolved to real
--    object ids; the query that finds them is:
--        SELECT DISTINCT requester_oid FROM change_request WHERE requester_oid LIKE 'supabase:%';

-- 7. THE LEGACY HAS A THIRD NOTE TYPE
--
--    cr_notes carries note_type='created' — the system entry written when a request is
--    raised. The constraint allowed only 'note' and 'status_change', so the import
--    failed on it.
--
--    Kept rather than mapped to 'note'. The legacy renders anything that is not 'note'
--    as a SYSTEM entry (legacy/change-request.js:860); collapsing 'created' into 'note'
--    would redisplay an automatic record as a person's comment, which is a small lie
--    that survives forever in the record.
ALTER TABLE change_request_note DROP CONSTRAINT IF EXISTS change_request_note_note_type_check;
ALTER TABLE change_request_note ADD CONSTRAINT change_request_note_note_type_check
  CHECK (note_type IN ('note', 'created', 'status_change'));

-- 8. DROPDOWN OPTIONS WERE STORED AS HTML
--
--    dropdownsHTML held 16 blocks of raw <option> markup in a database column. That
--    is the single worst thing in the legacy config: presentation in the rate data,
--    unqueryable, and impossible to validate.
--
--    The import parses it into pricing_option rows instead. Two attributes have to
--    survive that, or the parse loses information the app needs:
--
--    option_type  from data-type. src/lib/adc.js:76 switches on it to decide whether a
--                 video selection is flat, per-camera or an expansion package. Without
--                 it every tier prices as flat.
--    tooltip      from title. Multi-line guidance an estimator reads while choosing —
--                 "Base package: 4 cameras, 3,000 clips" and so on. Dropping it would
--                 silently remove help text nobody would notice missing until asked.
ALTER TABLE pricing_option ADD COLUMN IF NOT EXISTS option_type varchar(30);
ALTER TABLE pricing_option ADD COLUMN IF NOT EXISTS tooltip     text;
