-- ============================================================================
-- P1-SSE — PostgreSQL schema
--
-- Replaces db/schema.sql (Azure SQL / T-SQL). PostgreSQL, not Azure SQL, for two
-- reasons: the organisation already runs two shared PostgreSQL Flexible Servers
-- for the estimator and F.R.E.D, so another database on them costs nothing
-- marginal where an Azure SQL instance is a new recurring bill; and it reuses
-- tooling already hardened in production — passwordless managed-identity
-- connections, per-app CONNECT isolation, the migration runner, and 35-day
-- point-in-time restore. One database technology across three apps instead of two.
--
-- The engine swap is nearly free RIGHT NOW because nothing is provisioned and no
-- data exists here yet. After go-live it would not be.
--
-- WHAT THIS REPLACES ON THE LEGACY STACK
--   app_rates.config (one Supabase JSON blob)  → the normalised rate tables below
--   localStorage / .p1est files on OneDrive     → customer / site / quote / contract
--   cr_* Supabase tables + storage bucket       → the change_request_* tables below
--   Supabase Auth accounts                      → Entra (no identity stored here)
--
-- CONVENTIONS, and why they differ from the T-SQL original
--   snake_case: PostgreSQL folds unquoted identifiers to lower case, so a T-SQL
--     "ProductId" becomes "productid" — unreadable. Renaming is free because the
--     data-access layer is being rewritten for the engine change anyway.
--   jsonb, not text + a validity CHECK: jsonb validates on write by definition, so
--     the ISJSON() constraints in the original are unnecessary here, and the column
--     stays queryable.
--   timestamptz, not naive datetimes: quotes and change requests are timestamped
--     across a DST boundary twice a year.
--
-- Idempotent throughout (IF NOT EXISTS), so it doubles as the baseline the
-- migration runner applies on every deploy.
-- ============================================================================

-- ===========================================================================
-- 1. RATE CONFIGURATION — replaces app_rates.config
-- ===========================================================================

CREATE TABLE IF NOT EXISTS product (
  product_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag         varchar(20) NOT NULL UNIQUE      -- was app_rates.app, e.g. 'sse'
);

-- One row per published rate set. Old profiles are kept so a historical quote can
-- still be explained: every quote pins the profile it was priced with.
CREATE TABLE IF NOT EXISTS rate_profile (
  rate_profile_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      int NOT NULL REFERENCES product(product_id),
  version         int NOT NULL,
  is_active       boolean NOT NULL DEFAULT false,
  effective_from  timestamptz NOT NULL DEFAULT now(),
  created_by      varchar(200),                 -- Entra user principal name
  -- Alarm.com's published price sheet, stored as published. A VENDOR sheet, not
  -- Point 1's rates: reissued wholesale, never edited a cell at a time, and consumed
  -- as a tree by src/lib/adc.js. Point 1's own rates are normalised below.
  adc             jsonb,
  created_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_rate_profile_product_version UNIQUE (product_id, version)
);

-- "Only one active profile per product", enforced by the database rather than by
-- application discipline. A partial unique index is PostgreSQL's equivalent of the
-- original's filtered index.
CREATE UNIQUE INDEX IF NOT EXISTS ux_rate_profile_one_active_per_product
  ON rate_profile (product_id) WHERE is_active;

-- Scalar labor/margin defaults. One row per profile.
-- (was P1_RATES.laborBillDefault, laborCostPerHr, laborSellDefault, svcGM,
--  subMarkup, avMaintGM, matMarkup, tmSubGM, overheadRate)
CREATE TABLE IF NOT EXISTS labor_rate (
  rate_profile_id     int PRIMARY KEY REFERENCES rate_profile(rate_profile_id),
  labor_cost_per_hr   numeric(10,2) NOT NULL,
  labor_bill_default  numeric(10,2) NOT NULL,
  labor_sell_default  numeric(10,2) NOT NULL,
  svc_gm              numeric(5,2)  NOT NULL,   -- percent, e.g. 45.00
  sub_markup          numeric(5,2)  NOT NULL,
  av_maint_gm         numeric(5,2)  NOT NULL,
  mat_markup          numeric(5,2)  NOT NULL,
  tm_sub_gm           numeric(5,2)  NOT NULL,
  overhead_rate       numeric(5,2)  NOT NULL
);

-- Service-call multipliers (was svcStraight / svcTimeAndHalf / svcDoubleTime,
-- priorityMultiplier, premierMultiplier)
CREATE TABLE IF NOT EXISTS service_call_rate (
  rate_profile_id      int PRIMARY KEY REFERENCES rate_profile(rate_profile_id),
  straight_time_rate   numeric(10,2) NOT NULL,
  time_and_half_rate   numeric(10,2) NOT NULL,
  double_time_rate     numeric(10,2) NOT NULL,
  priority_multiplier  numeric(5,2)  NOT NULL,
  premier_multiplier   numeric(5,2)  NOT NULL
);

-- Monitoring RMR base/addon (was monBase, monAddon)
CREATE TABLE IF NOT EXISTS monitoring_rate (
  rate_profile_id int PRIMARY KEY REFERENCES rate_profile(rate_profile_id),
  base_rate       numeric(10,2) NOT NULL,
  addon_rate      numeric(10,2) NOT NULL
);

-- Access-control door pricing (was doorRateSACP / doorRateStd)
CREATE TABLE IF NOT EXISTS door_rate (
  rate_profile_id int PRIMARY KEY REFERENCES rate_profile(rate_profile_id),
  sacp_rate       numeric(10,2) NOT NULL,
  standard_rate   numeric(10,2) NOT NULL
);

-- Door bundle break points (was the doorBundlesSACP / doorBundlesStd arrays)
CREATE TABLE IF NOT EXISTS door_bundle (
  door_bundle_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rate_profile_id int NOT NULL REFERENCES rate_profile(rate_profile_id),
  bundle_type     varchar(10) NOT NULL CHECK (bundle_type IN ('SACP','Standard')),
  min_doors       int NOT NULL,
  max_doors       int,                       -- NULL = unbounded top tier
  price           numeric(10,2) NOT NULL,
  sort_order      int NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_door_bundle_profile
  ON door_bundle (rate_profile_id, bundle_type, sort_order);

-- Video monitoring pricing (was videoExpansionBase, videoSvr)
CREATE TABLE IF NOT EXISTS video_rate (
  rate_profile_id     int PRIMARY KEY REFERENCES rate_profile(rate_profile_id),
  expansion_base_rate numeric(10,2) NOT NULL,
  server_rate         numeric(10,2) NOT NULL
);

-- Central station / GCS pricing by system type
CREATE TABLE IF NOT EXISTS gcs_rate (
  rate_profile_id     int PRIMARY KEY REFERENCES rate_profile(rate_profile_id),
  fire_rate           numeric(10,2) NOT NULL,
  burg_rate           numeric(10,2) NOT NULL,
  residential_rate    numeric(10,2) NOT NULL,
  two_way_rate        numeric(10,2) NOT NULL,
  sf_burg_residential numeric(10,2) NOT NULL,
  sf_burg_commercial  numeric(10,2) NOT NULL
);

-- Minimum RMR floors by system/site type.
--
-- NOTE: src/lib/calc.js:102-111 preserves a legacy bug where this floor never
-- applies, because of a system-type string mismatch. Kept for parity. The
-- migration plan calls for an explicit business decision from the estimating lead
-- before the parity harness is trusted — the data model is not the problem.
CREATE TABLE IF NOT EXISTS min_rmr_rate (
  rate_profile_id   int PRIMARY KEY REFERENCES rate_profile(rate_profile_id),
  commercial_floor  numeric(10,2) NOT NULL,
  residential_floor numeric(10,2) NOT NULL,
  two_way_floor     numeric(10,2) NOT NULL
);

-- Flat named rates that do not justify a table of their own (ulCerts, pmVisitRate)
CREATE TABLE IF NOT EXISTS misc_rate (
  rate_profile_id int NOT NULL REFERENCES rate_profile(rate_profile_id),
  rate_key        varchar(50) NOT NULL,
  rate_value      numeric(10,2) NOT NULL,
  PRIMARY KEY (rate_profile_id, rate_key)
);

-- SLA service tiers (was tierRates + tierRatesLabel)
CREATE TABLE IF NOT EXISTS tier_rate (
  tier_rate_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rate_profile_id int NOT NULL REFERENCES rate_profile(rate_profile_id),
  tier_name       varchar(50) NOT NULL,      -- 'Standard', 'Priority', 'Premier'
  label           varchar(100),
  -- Straight time, kept so existing readers are unaffected.
  rate            numeric(10,2) NOT NULL,
  -- The real config carries three rates per tier. A single rate meant after-hours and
  -- holiday work quoted at the straight-time figure — an undercharge exactly when the
  -- work costs most.
  straight_time   numeric(10,2),
  time_and_half   numeric(10,2),
  double_time     numeric(10,2),
  sort_order      int NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_tier_rate_profile ON tier_rate (rate_profile_id, sort_order);

-- Pricing dropdown menus, replacing the stored raw markup in dropdownsHTML.
-- dropdown_group is the old element id ('adc-video', 'adc-base', 'connectone',
-- 'alarmnet'). React renders real <option> elements from these rows instead of
-- injecting HTML from the database.
CREATE TABLE IF NOT EXISTS pricing_option (
  pricing_option_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rate_profile_id   int NOT NULL REFERENCES rate_profile(rate_profile_id),
  dropdown_group    varchar(50) NOT NULL,
  option_value      varchar(50) NOT NULL,
  label             varchar(200) NOT NULL,
  price             numeric(10,2),
  -- From the legacy data-type attribute. adc.js:76 switches on it to decide whether a
  -- video selection is flat, per-camera or an expansion package.
  option_type       varchar(30),
  -- The legacy title attribute: multi-line guidance an estimator reads while choosing.
  tooltip           text,
  sort_order        int NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_pricing_option_profile
  ON pricing_option (rate_profile_id, dropdown_group, sort_order);

-- ===========================================================================
-- 2. BUSINESS DATA — was localStorage and .p1est files on OneDrive
-- ===========================================================================

CREATE TABLE IF NOT EXISTS customer (
  customer_id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            varchar(200) NOT NULL,
  contact_name    varchar(200),
  phone           varchar(30),
  email           varchar(200),
  billing_address varchar(300),
  owner_oid       varchar(100) NOT NULL,     -- Entra object id of the creator
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Shared between Quote Builder and Monitoring Contracts, per the legacy UI note
-- "Sites are shared with the Monitoring Contracts tab."
CREATE TABLE IF NOT EXISTS site (
  site_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  int NOT NULL REFERENCES customer(customer_id),
  label        varchar(100),                 -- 'Site 1', 'Site 2', ...
  address      varchar(300) NOT NULL,
  city         varchar(100),
  state        char(2),
  zip          varchar(10),
  monthly_rate numeric(10,2),
  sort_order   int NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_site_customer ON site (customer_id, sort_order);

CREATE TABLE IF NOT EXISTS quote (
  quote_id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     int NOT NULL REFERENCES customer(customer_id),
  -- Pins the rates this quote was priced with, so re-opening an old quote does
  -- not silently reprice it against today's numbers.
  rate_profile_id int NOT NULL REFERENCES rate_profile(rate_profile_id),
  estimate_type   varchar(30) NOT NULL,      -- 'time_and_materials' | 'flat_rate'
  system_type     varchar(50),
  site_type       varchar(30),               -- 'Residential' | 'Commercial'
  form_data       jsonb NOT NULL,            -- line items, materials, BOM, T&M
  recommended_rmr numeric(10,2),
  monitoring_rmr  numeric(10,2),
  owner_oid       varchar(100) NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  -- Two estimators editing one quote is the realistic conflict. Bumped on every
  -- update; the API compares it and refuses a stale write rather than letting the
  -- later save silently win.
  row_version     int NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS ix_quote_customer ON quote (customer_id);
CREATE INDEX IF NOT EXISTS ix_quote_owner ON quote (owner_oid);

CREATE TABLE IF NOT EXISTS contract (
  contract_id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     int NOT NULL REFERENCES customer(customer_id),
  rate_profile_id int NOT NULL REFERENCES rate_profile(rate_profile_id),
  service_tier    varchar(50),
  term_months     int,
  form_data       jsonb NOT NULL,            -- PM checklist, response times, exclusions
  signed_at       timestamptz,
  owner_oid       varchar(100) NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  row_version     int NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS ix_contract_customer ON contract (customer_id);

CREATE TABLE IF NOT EXISTS agreement (
  agreement_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  int NOT NULL REFERENCES customer(customer_id),
  form_data    jsonb NOT NULL,
  owner_oid    varchar(100) NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- An agreement can cover several sites — mirrors the legacy chip-selection UI.
CREATE TABLE IF NOT EXISTS agreement_site (
  agreement_id int NOT NULL REFERENCES agreement(agreement_id) ON DELETE CASCADE,
  site_id      int NOT NULL REFERENCES site(site_id),
  PRIMARY KEY (agreement_id, site_id)
);

-- ===========================================================================
-- 3. CHANGE REQUESTS — replaces the cr_* Supabase tables and its storage bucket
--
-- NO PROFILES TABLE, deliberately. The legacy cr_profiles held id / email /
-- display_name / is_developer, keyed to a Supabase Auth account. Identity comes
-- from Entra now, so there is nothing to store: the requester's object id, email
-- and name are snapshotted onto the row at write time (which is what a list view
-- needs anyway, and keeps the record readable if someone leaves), and
-- is_developer becomes an Entra group checked in the API — never a column, so it
-- cannot be edited by the thing it governs.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS change_request (
  change_request_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app               varchar(60) NOT NULL,    -- which app raised it ('SSE', 'F.R.E.D', ...)
  page              varchar(120),
  url               varchar(1000),
  request_type      varchar(20) NOT NULL
                      CHECK (request_type IN ('change','suggestion','bug')),
  priority          varchar(10) NOT NULL DEFAULT 'normal'
                      CHECK (priority IN ('low','normal','high')),
  status            varchar(20) NOT NULL DEFAULT 'open'
                      CHECK (status IN ('open','in_progress','done','wont_do')),
  title             varchar(200) NOT NULL,
  description       text NOT NULL,
  desired_result    text,
  requester_oid     varchar(100) NOT NULL,   -- Entra object id
  requester_email   varchar(200),
  requester_name    varchar(200),
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  completed_at      timestamptz,
  -- Set only by the legacy import, so a re-run updates instead of duplicating.
  legacy_id         int
);
CREATE INDEX IF NOT EXISTS ix_change_request_status ON change_request (status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_change_request_requester ON change_request (requester_oid);

-- Attachments. The bytes live in Azure Blob Storage, not here — storage_path is
-- the blob name, keeping the legacy "<requestId>/<timestamp>-<n>-<name>" shape so
-- existing objects can be copied across without rewriting paths.
--
-- Downloads do NOT use a shared-key SAS: the storage account has shared-key access
-- disabled, exactly as F.R.E.D's does. Either stream through the API (F.R.E.D's
-- /api/photos pattern) or mint a user-delegation SAS with the managed identity.
CREATE TABLE IF NOT EXISTS change_request_file (
  change_request_file_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  change_request_id      int NOT NULL REFERENCES change_request(change_request_id) ON DELETE CASCADE,
  file_role              varchar(20) NOT NULL
                           CHECK (file_role IN ('export','screenshot','fixed_export')),
  storage_path           varchar(500) NOT NULL,
  filename               varchar(255) NOT NULL,
  mime_type              varchar(120),
  -- 25 MB, matching the limit the legacy bucket enforced. Kept in the schema so
  -- the ceiling survives a rewrite of the upload path.
  size_bytes             bigint NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 26214400),
  uploaded_by_oid        varchar(100) NOT NULL,
  uploaded_by_name       varchar(200),
  uploaded_at            timestamptz NOT NULL DEFAULT now(),
  legacy_id              int
);
CREATE INDEX IF NOT EXISTS ix_change_request_file_request
  ON change_request_file (change_request_id, uploaded_at);

CREATE TABLE IF NOT EXISTS change_request_note (
  change_request_note_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  change_request_id      int NOT NULL REFERENCES change_request(change_request_id) ON DELETE CASCADE,
  note_type              varchar(20) NOT NULL DEFAULT 'note'
                           CHECK (note_type IN ('note','created','status_change')),
  body                   text NOT NULL,
  author_oid             varchar(100) NOT NULL,
  author_email           varchar(200),
  author_name            varchar(200),
  created_at             timestamptz NOT NULL DEFAULT now(),
  legacy_id              int
);
CREATE INDEX IF NOT EXISTS ix_change_request_note_request
  ON change_request_note (change_request_id, created_at DESC);

-- ===========================================================================
-- 4. VIEWS
-- ===========================================================================

-- Consumed by the rates endpoint.
CREATE OR REPLACE VIEW active_rate_profile AS
SELECT p.tag AS product_tag, rp.rate_profile_id, rp.version, rp.effective_from
FROM rate_profile rp
JOIN product p ON p.product_id = rp.product_id
WHERE rp.is_active;

-- Replaces cr_list_view. Counts come from the view rather than a second round
-- trip, which is what the legacy list did per row.
CREATE OR REPLACE VIEW change_request_list AS
SELECT r.*,
       (SELECT count(*) FROM change_request_note n
         WHERE n.change_request_id = r.change_request_id) AS note_count,
       (SELECT count(*) FROM change_request_file f
         WHERE f.change_request_id = r.change_request_id) AS file_count
FROM change_request r;

-- Replaces cr_notes_view. The author name is already on the row, so this exists
-- for shape compatibility with the legacy client rather than to perform a join.
CREATE OR REPLACE VIEW change_request_note_list AS
SELECT n.* FROM change_request_note n;

-- ── Reference lists ─────────────────────────────────────────────────────────
-- The legacy kept estimators, vendors and manufacturers inside the rates blob. They
-- are not rates, and binding them to rate_profile would mean publishing a new rate
-- profile to add a colleague — a repricing event to record a name. Separate tables,
-- editable without touching pricing.
--
-- is_active rather than DELETE: an estimator who leaves still appears on the quotes
-- they prepared, and removing the row would orphan that history.
CREATE TABLE IF NOT EXISTS estimator (
  estimator_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         varchar(200) NOT NULL,
  email        varchar(200),
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now()
);
-- Case-insensitive so 'J.Smith@' and 'j.smith@' are one person; partial so rows
-- without an email are allowed rather than colliding on NULL.
CREATE UNIQUE INDEX IF NOT EXISTS uq_estimator_email
  ON estimator (lower(email)) WHERE email IS NOT NULL;

CREATE TABLE IF NOT EXISTS vendor (
  vendor_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_key  varchar(80) NOT NULL,
  display     varchar(200) NOT NULL,
  -- The legacy matches vendor names from imported spreadsheets against these.
  aliases     jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_vendor_key ON vendor (lower(vendor_key));

CREATE TABLE IF NOT EXISTS manufacturer (
  manufacturer_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            varchar(200) NOT NULL,
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_manufacturer_name ON manufacturer (lower(name));

-- Legacy ids, so a repeated import updates rather than duplicating. NULL for anything
-- created in the new app.
CREATE UNIQUE INDEX IF NOT EXISTS uq_change_request_legacy
  ON change_request (legacy_id) WHERE legacy_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_change_request_file_legacy
  ON change_request_file (legacy_id) WHERE legacy_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_change_request_note_legacy
  ON change_request_note (legacy_id) WHERE legacy_id IS NOT NULL;
